CREATE TABLE IF NOT EXISTS users (
  id                INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  role_id           TINYINT UNSIGNED NOT NULL,
  department_id     INT UNSIGNED NULL,
  student_number    VARCHAR(30) NULL UNIQUE,
  first_name        VARCHAR(80) NOT NULL,
  last_name         VARCHAR(80) NOT NULL,
  email             VARCHAR(150) NOT NULL UNIQUE,
  password_hash     VARCHAR(255) NOT NULL,
  is_active         TINYINT(1) NOT NULL DEFAULT 0,
  is_email_verified TINYINT(1) NOT NULL DEFAULT 0,
  profile_photo     VARCHAR(255) NULL,
  created_at        DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at        DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at        DATETIME NULL,
  FOREIGN KEY (role_id)       REFERENCES roles(id),
  FOREIGN KEY (department_id) REFERENCES departments(id),
  INDEX idx_email (email),
  INDEX idx_role  (role_id)
);
