CREATE TABLE IF NOT EXISTS thesis_submissions (
  id               INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  student_id       INT UNSIGNED NOT NULL,
  adviser_id       INT UNSIGNED NULL,
  department_id    INT UNSIGNED NOT NULL,
  type             ENUM('thesis','capstone') NOT NULL DEFAULT 'thesis',
  title            VARCHAR(500) NOT NULL,
  abstract         TEXT NULL,
  keywords         VARCHAR(500) NULL,
  status           ENUM('draft','submitted','under_review','approved','rejected','revision_required') NOT NULL DEFAULT 'draft',
  school_year      VARCHAR(10) NOT NULL,
  semester         ENUM('1st','2nd','summer') NOT NULL,
  submitted_at     DATETIME NULL,
  approved_at      DATETIME NULL,
  created_at       DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at       DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at       DATETIME NULL,
  FOREIGN KEY (student_id)    REFERENCES users(id),
  FOREIGN KEY (adviser_id)    REFERENCES users(id),
  FOREIGN KEY (department_id) REFERENCES departments(id),
  FULLTEXT INDEX ft_title    (title),
  FULLTEXT INDEX ft_abstract (abstract),
  INDEX idx_status    (status),
  INDEX idx_school_yr (school_year)
);
