CREATE TABLE IF NOT EXISTS venues (
  id         INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name       VARCHAR(150) NOT NULL,
  location   VARCHAR(255) NULL,
  capacity   TINYINT UNSIGNED NULL,
  is_active  TINYINT(1) NOT NULL DEFAULT 1,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
