CREATE TABLE IF NOT EXISTS archive (
  id             INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  submission_id  INT UNSIGNED NOT NULL UNIQUE,
  document_id    INT UNSIGNED NOT NULL,
  title          VARCHAR(500) NOT NULL,
  abstract       TEXT NULL,
  authors        VARCHAR(500) NOT NULL,
  adviser        VARCHAR(200) NULL,
  department_id  INT UNSIGNED NOT NULL,
  school_year    VARCHAR(10) NOT NULL,
  semester       ENUM('1st','2nd','summer') NOT NULL,
  keywords       VARCHAR(500) NULL,
  type           ENUM('thesis','capstone') NOT NULL,
  archived_at    DATETIME DEFAULT CURRENT_TIMESTAMP,
  archived_by    INT UNSIGNED NOT NULL,
  download_count INT UNSIGNED NOT NULL DEFAULT 0,
  FOREIGN KEY (submission_id) REFERENCES thesis_submissions(id),
  FOREIGN KEY (document_id)   REFERENCES submission_documents(id),
  FOREIGN KEY (department_id) REFERENCES departments(id),
  FOREIGN KEY (archived_by)   REFERENCES users(id),
  FULLTEXT INDEX ft_archive_title    (title),
  FULLTEXT INDEX ft_archive_abstract (abstract),
  FULLTEXT INDEX ft_archive_keywords (keywords),
  INDEX idx_dept_year (department_id, school_year)
);
